[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$major.$minor.$patch$prerelease"
version = "0.0.0"
version_files = [
    ".cz.toml",
    "app/package.json:version"
    "Dockerfile:org.label-schema.version"
]
