#!/bin/bash

echo Are you sure you want to deploy in production? \(ctrl-c if not\)
read

WHO=`whoami`
LEMVERSE_CHANNEL="${LEMVERSE_CHANNEL:-#dev-notifications}"

command -v slack >/dev/null 2>&1 && slack chat send " --------------------:mario_luigi_dance::mario_luigi_dance: *lemverse* starting deployment by _ $WHO _... :mario_luigi_dance::mario_luigi_dance:-------------------" "$LEMVERSE_CHANNEL" > /dev/null

if [ -f ~/.nvm/nvm.sh ]; then
  echo 'sourcing nvm from ~/.nvm'
  . ~/.nvm/nvm.sh
elif command -v brew; then
  # https://docs.brew.sh/Manpage#--prefix-formula
  BREW_PREFIX=$(brew --prefix nvm)
  if [ -f "$BREW_PREFIX/nvm.sh" ]; then
    echo "sourcing nvm from brew ($BREW_PREFIX)"
    . $BREW_PREFIX/nvm.sh
  fi
fi
nvm use 12
../mup/bin/mup deploy

command -v slack >/dev/null 2>&1 && slack chat send " ---------------------:mario_luigi_dance::mario_luigi_dance: *lemverse* deployed by _ $WHO _ :mario_luigi_dance::mario_luigi_dance:-------------------" "$LEMVERSE_CHANNEL" > /dev/null
