name: Build Docker Image

on:
  push:
    tags:
      - '*'
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: "Deploy image on Dockerhub"
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: '${{ secrets.PERSONAL_ACCESS_TOKEN }}'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get smart tag
        id: prepare
        uses: Surgo/docker-smart-tag-action@v1
        with:
          docker_image: ${{GITHUB_REPOSITORY}}
      - run: echo ${{ steps.prepare.outputs.tag }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.prepare.outputs.tag }}
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
      - name: Image digest
        run: echo ${{ steps.prepare.outputs.tag }}     
      - name: Get the last version change
        id: lastchanges
        uses: jupyter-naas/get-chagelog-diff@v1.0.0
      - name: Changelog digest
        run: echo ${{ steps.prepare.outputs.tag }}     
      # - name: Slack notification
      #   env:
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      #     SLACK_USERNAME: L3mBot # Optional. (defaults to webhook app)
      #     SLACK_CHANNEL: l3mpire-ci # Optional. (defaults to webhook)
      #     SLACK_AVATAR: repository
      #     SLACK_CUSTOM_PAYLOAD: '{"attachments":[{"color":"#47dd82","blocks":[{"type":"section","block_id":"section567","text":{"type":"mrkdwn","text":"<https://github.com/{{ GITHUB_REPOSITORY }}|{{ GITHUB_REPOSITORY }}>\nAvailable to pip and docker hub.\n*Version*\n${{ steps.get-latest-tag.outputs.tag }}\n ${{ steps.lastchanges.outputs.lastChanges }}"},"accessory":{"type":"image","image_url":"https://github.com/l3mpire/lemverse/raw/master/app/public/lemverse.png","alt_text":"L3mpire logo"}}]}]}'
      #   uses: Ilshidur/action-slack@2.0.2
