#!/bin/bash

if [ -f ~/.nvm/nvm.sh ]; then
  echo 'sourcing nvm from ~/.nvm'
  . ~/.nvm/nvm.sh
elif command -v brew; then
  # https://docs.brew.sh/Manpage#--prefix-formula
  BREW_PREFIX=$(brew --prefix nvm)
  if [ -f "$BREW_PREFIX/nvm.sh" ]; then
    echo "sourcing nvm from brew ($BREW_PREFIX)"
    . $BREW_PREFIX/nvm.sh
  fi
fi

nvm use 14

GH_TOKEN=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 npm run dist

open https://github.com/l3mpire/lemverse/releases
echo release the draft version
echo click on update
echo restart lemverse
